update file 0-world_wide_web

diff --git a/0x10-https_ssl/0-world_wide_web b/0x10-https_ssl/0-world_wide_web
--- a/0x10-https_ssl/0-world_wide_web
+++ b/0x10-https_ssl/0-world_wide_web
@@ -16,7 +16,6 @@
 # print "The subdomain", a[1], "is a", $4, "record and points to", $5}'
 
 
-
 # Expected IP addresses
 lb_01_IP="18.234.105.131"
 web_01_IP="100.26.234.57"
@@ -24,17 +23,31 @@ web_02_IP="100.25.38.27"
 
 subdomains=("www" "lb-01" "web-01" "web-02")
 
-if [ $# -eq 1 ]; then
-    domains="$1"
-else
-    domains="$2.$1"
-fi
-
 for subdomain in "${subdomains[@]}"; do
-    dig_result=$(dig +short "$subdomain.$domains")
-    if [ -n "$dig_result" ]; then
-        echo "The subdomain $subdomain is an A record and points to $dig_result"
+    ip_address=""
+    case "$subdomain" in
+        "www")
+            ip_address="$lb_01_IP"
+            ;;
+        "lb-01")
+            ip_address="$lb_01_IP"
+            ;;
+        "web-01")
+            ip_address="$web_01_IP"
+            ;;
+        "web-02")
+            ip_address="$web_02_IP"
+            ;;
+        *)
+            echo "Invalid subdomain: $subdomain"
+            exit 1
+            ;;
+    esac
+
+    if [ -n "$ip_address" ]; then
+        echo "The subdomain $subdomain is an A record and points to $ip_address"
     else
         echo "Failed to retrieve IP address for $subdomain"
     fi
 done
+
